# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-20.04
  tools:
    # this is required to make conda works
    # ref https://github.com/readthedocs/readthedocs.org/issues/8595
    python: mambaforge-4.10

conda:
  environment: environment.yml

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: en/conf.py
